on:
  push:
    branches:
    - main
    - bellissima
  pull_request:
    branches:
    - main
    - bellissima
jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Build
      run: dotnet build --configuration Release